version: "3.8"
services:
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWD:-secret}
      PGDATABASE: ${DB_NAME:-db}
      PGUSER: ${DB_USER:-postgres}
      PGPASSWORD: ${DB_PASSWD:-secret}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT:-5432}:5432

  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    # ports:
    #   - 127.0.0.1:${LOCAL_REDIS_PORT:-6379}:6379

  es:
    image: elasticsearch:8.3.3
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      discovery.type: single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    # ports:
    #   - 127.0.0.1:${LOCAL_ES_PORT:-9200}:9200

  web:
    build: .
    depends_on:
      - db
      - redis
      - es
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-5000}:5000
    environment:
      DB_HOST: db
      REDIS_URI: redis://redis:6379
      ESEARCH_URI: http://es:9200
    restart: unless-stopped

volumes:
  db_data:
  redis-data:
  es-data:
