version: "3.8"
services:
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWD:-secret}
      PGDATABASE: ${DB_NAME:-db}
      PGUSER: ${DB_USER:-root}
      PGPASSWORD: ${DB_PASSWD:-secret}
    ports:
      - 127.0.0.1:${DB_PORT:-5432}:5432

  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

  esearch:
    image: elasticsearch:8.3.3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048m
        reservations:
          memory: 100m
    environment:
      discovery.type: single-node
    volumes:
      - esearch-data:/usr/share/elasticsearch/data

  web:
    build: .
    depends_on:
      - db
      - redis
      - esearch
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-5000}:5000
    environment:
      DB_HOST: db
    restart: unless-stopped

volumes:
  db_data:
  redis-data:
  esearch-data:
